### ISSUE TITLE
cuda_and_trace_event branch compile failed

### ISSUE THREAD

**Issue by weilewei** [khuck/xpress-apex#124]
The cmake configuration is nearly the same in https://github.com/khuck/xpress-apex/issues/123#issuecomment-663927840
error log:

FAILED: apex/src/apex/libhpx_apex.so.1.5.0 
: && /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-8.1.1/spectrum-mpi-10.3.1.2-20200121-chae23sgwacfeot7vxkpfboz6wao2c33/bin/mpicxx -fPIC -O3 -DNDEBUG  -Wl,-z,defs -fvisibility=hidden   -Wl,-no-as-needed -shared -Wl,-soname,libhpx_apex.so.1 -o apex/src/apex/libhpx_apex.so.1.5.0 apex/src/apex/CMakeFiles/apex.dir/apex.cpp.o apex/src/apex/CMakeFiles/apex.dir/apex_options.cpp.o apex/src/apex/CMakeFiles/apex.dir/apex_policies.cpp.o apex/src/apex/CMakeFiles/apex.dir/concurrency_handler.cpp.o apex/src/apex/CMakeFiles/apex.dir/event_listener.cpp.o apex/src/apex/CMakeFiles/apex.dir/policy_handler.cpp.o apex/src/apex/CMakeFiles/apex.dir/handler.cpp.o apex/src/apex/CMakeFiles/apex.dir/profiler_listener.cpp.o apex/src/apex/CMakeFiles/apex.dir/task_identifier.cpp.o apex/src/apex/CMakeFiles/apex.dir/tau_listener.cpp.o apex/src/apex/CMakeFiles/apex.dir/tau_dummy.cpp.o apex/src/apex/CMakeFiles/apex.dir/thread_instance.cpp.o apex/src/apex/CMakeFiles/apex.dir/utils.cpp.o apex/src/apex/CMakeFiles/apex.dir/proc_read.cpp.o apex/src/apex/CMakeFiles/apex.dir/otf2_listener.cpp.o apex/src/apex/CMakeFiles/apex.dir/activity_trace_async.cpp.o  -Wl,-rpath,/gpfs/alpine/proj-shared/cph102/weile/dev/src/hpx_apex/hpx/build_hpxmaster_apexcuda_RelWithDebInfo/lib:/gpfs/alpine/proj-shared/cph102/weile/dev/install/boost/1.73.0/lib:/gpfs/alpine/proj-shared/cph102/weile/dev/install/jemalloc/5.1.0/lib:/gpfs/alpine/proj-shared/cph102/weile/dev/install/hwloc/2.2.0/lib:/sw/summit/cuda/10.1.105/lib64:/sw/summit/cuda/10.1.105/extras/CUPTI/lib64:/gpfs/alpine/proj-shared/cph102/weile/dev/src/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/otf2-2.2-ihp5wgzz6rojxunxdet45s7zpnj4agt3/lib:  /usr/lib64/libdl.so  lib/libhpx.so.1.5.0  /gpfs/alpine/proj-shared/cph102/weile/dev/install/boost/1.73.0/lib/libboost_program_options.so  /gpfs/alpine/proj-shared/cph102/weile/dev/install/boost/1.73.0/lib/libboost_filesystem.so  /gpfs/alpine/proj-shared/cph102/weile/dev/install/jemalloc/5.1.0/lib/libjemalloc.so  /gpfs/alpine/proj-shared/cph102/weile/dev/install/hwloc/2.2.0/lib/libhwloc.so  -latomic  -ldl  -lrt  /sw/summit/cuda/10.1.105/lib64/libcudart.so  /sw/summit/cuda/10.1.105/extras/CUPTI/lib64/libcupti.so  /gpfs/alpine/proj-shared/cph102/weile/dev/src/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/otf2-2.2-ihp5wgzz6rojxunxdet45s7zpnj4agt3/lib/libotf2.so && :
apex/src/apex/CMakeFiles/apex.dir/apex.cpp.o: In function `apex::apex::_initialize()':
apex.cpp:(.text+0x28a0): undefined reference to `apex::trace_event_listener::trace_event_listener()'
apex/src/apex/CMakeFiles/apex.dir/activity_trace_async.cpp.o: In function `store_profiler_data(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int)':
activity_trace_async.cpp:(.text+0x144c): undefined reference to `apex::trace_event_listener::on_async_event(unsigned int, unsigned int, unsigned int, std::shared_ptr<apex::profiler>&)'
/usr/bin/ld: link errors found, deleting executable `apex/src/apex/libhpx_apex.so.1.5.0

**Comment by khuck** [comment]
Oh, I forgot to add a file to cmake. I'll get that in the morning, thanks!

**Comment by khuck** [comment]
I think it's fixed, please try again.  Thanks!
