### ISSUE TITLE
Profiling with TAU (with APEX) for an HPX program failed

### ISSUE THREAD

**Issue by nithin-nod** [khuck/xpress-apex#128]
I'm trying to use the TAU integration with APEX to profile an HPX program. I built HPX with APEX (using `HPX_WITH_APEX=TRUE` flag) and it works. However when I try to run the TAU profiler (after exporting APEX_TAU=1 & using `tau_exec` in the program run) I get the following error:
```
TAU libraries not loaded, TAU support unavailable:
	/path/to/hpx/install/lib/libhpx_apex.so.1: undefined symbol: Tau_init
```
Is TAU not supported anymore with APEX?

**Comment by khuck** [comment]
Yes, it's still supported - but you have to run with tau_exec.  APEX no longer builds with TAU linked in.  I don't have any explicit instructions for configuring TAU with APEX, but you can get TAU from `https://github.com/UO-OACISS/tau2`, and configure with `./configure -pthread ; make -j install` to build TAU.  The `tau_exec` executable will be in the `$arch/bin` directory.  you then run your program with `tau_exec -T serial,pthread <program> <args>`.  I'll try to put together a documented example on how to do it when I get a chance.

**Comment by nithin-nod** [comment]
I tried to run `tau_exec` with an HPX executable program just like how you mentioned but I get the following error:
```
./tau_exec: line 6: tau-config: command not found
./tau_exec: line 20: tau-config: command not found
./tau_exec: line 710: tau-config: command not found
./tau_exec: line 716: tau-config: command not found
Binding not found. Exiting...
```
To test out TAU, I ran the `doall.sh` and that seems to be successful.
Thank you for your response.

**Comment by khuck** [comment]
Did you add `tau_exec` to your path?  The `tau-config` program is a script called from the `tau_exec` script, and it requires that TAU be in your shell path.

**Comment by nithin-nod** [comment]
That fixed it, I misread the output after build to add the path. Thank you

**Comment by khuck** [comment]
@nithin-nod excellent!  Let me know if you run into any other problems...
