### ISSUE TITLE
Corrupt trace file/OTF2 generation for HPX/Phylanx Neural Network programs - Timestamp mismatch

### ISSUE THREAD

**Issue by nithin-nod** [khuck/xpress-apex#131]
I tried to generate a trace file for the following Phylanx program (https://github.com/STEllAR-GROUP/phylanx/blob/master/examples/algorithms/nn/nn_csv.cpp) but I hit the following error:

```
{stack-trace}: [OTF2] src/OTF2_Buffer.h:970: error: Parameter value out of range: Passed timestamp is smaller than last written one! (3863255470580896768 < 18446723372290448384)
OTF2 Error: INVALID_ARGUMENT, Parameter value out of range
[OTF2] src/OTF2_Buffer.h:970: error: Parameter value out of range: Passed timestamp is smaller than last written one! (3879047503580896768 < 18446723372290448384)
OTF2 Error: INVALID_ARGUMENT, Parameter value out of range
[OTF2] src/OTF2_Buffer.h:970: error: Parameter value out of range: Passed timestamp is smaller than last written one! (3879206416580896768 < 18446723372290448384)
OTF2 Error: INVALID_ARGUMENT, Parameter value out of range
[OTF2] src/OTF2_Buffer.h:970: error: Parameter value out of range: Passed timestamp is smaller than last written one! (3880040668580896768 < 18446723372290448384)
OTF2 Error: INVALID_ARGUMENT, Parameter value out of range
20 frames:
```

It seems like there is a mismatch in the timestamp that's passed to OTF buffer. I would think that this is a problem with OTF2 library but I have another HPX example (mnist training) which generates trace files up to a certain number of epochs and gets a similar error as above for more epoch numbers.

**Comment by nithin-nod** [comment]
I also came across similar error when trying to open a trace file in chrome:
![chrome_trace_error](https://user-images.githubusercontent.com/68087711/101303681-6c63ea00-37f3-11eb-8678-5b4a31946d10.png)

Please note that this doesn't always occur.

**Comment by khuck** [comment]
Yeah, there was an x86_64 bug in the conversion of the RDTSC counter to a timestamp.  Please use the latest develop branch (which disables the counter completely) or explicitly set `-DAPEX_USE_CLOCK_TIMESTAMP=TRUE` when you configure HPX.

**Comment by nithin-nod** [comment]
Thank you for clarifying Kevin!
