### ISSUE TITLE
APEX OTF2 Trace - timestamps not correct/missing timefactor

### ISSUE THREAD

**Issue by leonfse** [khuck/xpress-apex#133]
Hello, I am trying to get an OTF2 Trace from an HPX Application with APEX. While this succeeded, the result seems to contain some mistakes:
![grafik](https://user-images.githubusercontent.com/77839967/106153005-600a6680-617e-11eb-9005-04995a5f9374.png)

Unlike the OTF2 output the times from APEX_SCREEN_OUTPUT seem to be correct. So we thought, that the time factor might be missing from OTF2. Is this because of my build or might it have other reasons?

Built:
HPX 1.5.1 has been built with APEX and OTF2 (OTF 2.2) turned on:
cmake -DCMAKE_INSTALL_PREFIX=/opt/hpx -DHPX_WITH_APEX=TRUE -DAPEX_WITH_OTF2=TRUE -DOTF2_ROOT=/opt/otf2/lib/ ..

**Comment by leonfse** [comment]
Also wondering if APEX should show any User Funktions or just the HPX funktions in this case.

**Comment by khuck** [comment]
@leonfse what does the screen output show?

If you are running on an x86_64 system, It looks like you got burned by a bug that was introduced when CUPTI support was added.  Please add the following to your HPX CMake configuration - either `-DHPX_WITH_APEX_TAG=develop` or `-DAPEX_USE_CLOCK_TIMESTAMP=TRUE`.

**Comment by khuck** [comment]
> Also wondering if APEX should show any User Funktions or just the HPX funktions in this case.

APEX will only show the tasks that are scheduled by the HPX runtime, unless you add additional instrumentation.  See http://khuck.github.io/xpress-apex/spec/ for more info.

**Comment by leonfse** [comment]
-DHPX_WITH_APEX_TAG=develop has solved the Issue. Thank you very much!

**Comment by khuck** [comment]
Glad it worked, sorry for the bug!
