### ISSUE TITLE
Add multiple profiler_listener objects when queue is overloaded.

### ISSUE THREAD

**Issue by khuck** [khuck/xpress-apex#33]
With the std::async() tests, certain tests that generate lots of small tasks (fft for example) put more profiler objects in the queue than can be processed by one profiler_listener object. Do we need multiple? There appears plenty of CPU headroom due to the context switching between pthreads.

**Comment by nchaimov** [comment]
Do this as a policy: if queue is over some amount and idle rate is over some amount.

**Comment by khuck** [comment]
Going to close this. It was only an issue when evaluating silly benchmarks like the inncabs ones that spawn millions of tiny tasks that take longer to measure than to execute. Besides, we now spawn multiple threads at exit to clean up any remaining profiler objects on the queue and update the statistics, and that prevents long shutdown times when the queue processing gets bogged down (like in the benchmark case).
