### ISSUE TITLE
Runtime enable/disable of APEX

### ISSUE THREAD

**Issue by khuck** [khuck/xpress-apex#49]
IT would be nice to enable/disable APEX at runtime, either with an API call and/or an environment variable. 

Also, it would be nice to selectively enable/disable things, like "only collect PAPI counters for the next iteration or two" - so that we can "characterize" the tasks, without the overhead of always collecting measurements. 

Should we be able to selectively enable/disable specific timers for specific tasks? Good question.

**Comment by pmucci** [comment]
Or perhaps a non blocking socket that could be sent a control packet that could trigger a SIGIO to read and act upon it, should there be any external agents interested?

Apologies for brevity and errors as this was sent from my mobile device.

**Comment by khuck** [comment]
Control with a signal (SIGUSR, etc) could be an option - it would trigger APEX to read a configuration file?

**Comment by pmucci** [comment]
Possibly? Or take any number of other actions… What if APEX’s instrumentation and decision mechanism was ‘pluggable’, I’m hand-waving here… You mentioned before, should APEX instrument all tasks? That’s a good question. Would it make sense to always have to decide all of this in APEX code priori? Or what if this was an out-of-band decision mechanism, for the where, when of instrumentation as well as (possibly) other HPX variables and parameters? 

I shouldn’t be thinking about this. I should be thinking about how to get some funding.

Philip J. Mucci
Minimal Metrics LLC
7125 Wells Ave | Navarre FL 32566
Ph: 415.577.9899 | Fax: 415.689.3976  
www.minimalmetrics.com <http://www.minimalmetrics.com/>

**Comment by khuck** [comment]
Merged with commit 4bd5cbcf7e05273c82b1a7de6af4af1e2a9bc5f8.

There are now three environment variables with associated API calls:
    macro (APEX_DISABLE, disable, bool, false) \
    macro (APEX_SUSPEND, suspend, bool, false) \
    macro (APEX_PAPI_SUSPEND, papi_suspend, bool, false) \

The "disable" will do just that - prevent APEX from even initializing.
The "suspend" will tell APEX to stop processing timers and counters. All other API calls still work.
The "api_suspend" will tell APEX to stop reading PAPI counters for timers. This is useful when reading PAPI counters that don't change over time, and only need to be collected for a short period.
