### ISSUE TITLE
HPX applications aborts when APEX is enabled

### ISSUE THREAD

**Issue by shoshijak** [khuck/xpress-apex#79]
When running HPX applications with APEX enabled, I get the error message 

`assertion 'type_ == data_type_address' failed: HPX(assertion_failure)
Aborted (core dumped)`

However the HPX applications run normally when APEX is disabled (that is, if I build HPX without the option -DHPX_WITH_APEX=ON).

Here's the stack trace:
0	__GI_abort	/usr/lib/debug/lib/x86_64-linux-gnu/libc-2.23.so	51	0x7ffff45a1ec0	
1	hpx::detail::assertion_failed_msg	exception.cpp	492	0x7ffff61737b7	
2	hpx::detail::assertion_failed	exception.cpp	446	0x7ffff61732bb	
3	hpx::assertion_failed	exception.cpp	1245	0x7ffff6176df4	
4	hpx::util::thread_description::valid	thread_description.hpp	167	0x7ffff62bfc03	
5	hpx::util::thread_description::operator bool	thread_description.hpp	159	0x7ffff62bfba8	
6	hpx::threads::detail::create_work	create_work.hpp	46	0x7ffff62c2e17	
7	hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>>::create_work	thread_pool.cpp	202	0x7ffff6368e69	
8	hpx::threads::threadmanager_impl<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>>::register_work	threadmanager.cpp	246	0x7ffff63d17eb	
9	hpx::applier::register_work_plain	applier.cpp	257	0x7ffff6bc0388	
10	hpx::traits::detail::schedule_thread_helper::call<apex_internal_process_profiles_action>	action_schedule_thread.hpp	29	0x7ffff703723d	
11	hpx::traits::detail::call_schedule_thread<apex_internal_process_profiles_action>	action_schedule_thread.hpp	54	0x7ffff70351f3	
12	hpx::traits::action_schedule_thread<apex_internal_process_profiles_action, void>::call	action_schedule_thread.hpp	67	0x7ffff7031b97	
13	hpx::applier::detail::apply_helper<apex_internal_process_profiles_action, false>::call<>(hpx::threads::thread_init_data&&, hpx::naming::id_type const&, unsigned long, hpx::threads::thread_priority)	apply_helper.hpp	96	0x7ffff702ea03	
14	hpx::applier::detail::apply_l_p<apex_internal_process_profiles_action>(hpx::naming::id_type const&, hpx::naming::address&&, hpx::threads::thread_priority)	apply.hpp	196	0x7ffff70353e9	
15	hpx::detail::apply_impl<apex_internal_process_profiles_action>	apply_implementations.hpp	160	0x7ffff7031f9b	
16	hpx::apply_p<apex_internal_process_profiles_action>	apply.hpp	236	0x7ffff702eded	
17	hpx::detail::apply_dispatch<apex_internal_process_profiles_action, void>::call<hpx::actions::detail::plain_function, void (), apex_internal_process_profiles_action>(hpx::actions::basic_action<hpx::actions::detail::plain_function, void (), apex_internal_process_profiles_action>, hpx::naming::id_type const&)	apply.hpp	287	0x7ffff70227de	
18	hpx::apply<apex_internal_process_profiles_action&, hpx::naming::id_type>(apex_internal_process_profiles_action&, hpx::naming::id_type&&)	apply.hpp	118	0x7ffff70227de	
19	apex_schedule_process_profiles	profiler_listener.cpp	1495	0x7ffff70227de	
20	apex::profiler_listener::push_profiler	profiler_listener.cpp	1327	0x7ffff702642b	
21	apex::profiler_listener::_common_stop	profiler_listener.cpp	1359	0x7ffff70264ad	
22	apex::profiler_listener::on_stop	profiler_listener.cpp	1377	0x7ffff7021d60	
23	apex::stop	apex.cpp	524	0x7ffff6fe682e	
24	hpx::util::apex_wrapper::stop	apex.hpp	61	0x7ffff60d05a5	
25	hpx::threads::detail::scheduling_loop<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>>	scheduling_loop.hpp	500	0x7ffff62dd3a8	
26	hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>>::thread_func	thread_pool.cpp	648	0x7ffff636a93f	
27	boost::_mfi::mf3<void, hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>>, unsigned long, hpx::threads::topology const&, boost::barrier&>::operator()	mem_fn_template.hpp	393	0x7ffff63a207b	
28	boost::_bi::list4<boost::_bi::value<hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>> *>, boost::_bi::value<unsigned long>, boost::_bi::value<std::reference_wrapper<hpx::threads::topology const>>, boost::_bi::value<std::reference_wrapper<boost::barrier>>>::operator()<boost::_mfi::mf3<void, hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>>, unsigned long, hpx::threads::topology const&, boost::barrier&>, boost::_bi::list0>	bind.hpp	463	0x7ffff63a1963	
29	boost::_bi::bind_t<void, boost::_mfi::mf3<void, hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>>, unsigned long, hpx::threads::topology const&, boost::barrier&>, boost::_bi::list4<boost::_bi::value<hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>> *>, boost::_bi::value<unsigned long>, boost::_bi::value<std::reference_wrapper<hpx::threads::topology const>>, boost::_bi::value<std::reference_wrapper<boost::barrier>>>>::operator()	bind.hpp	1294	0x7ffff63a130c	
30	boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf3<void, hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>>, unsigned long, hpx::threads::topology const&, boost::barrier&>, boost::_bi::list4<boost::_bi::value<hpx::threads::detail::thread_pool<hpx::threads::policies::local_priority_queue_scheduler<boost::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>> *>, boost::_bi::value<unsigned long>, boost::_bi::value<std::reference_wrapper<hpx::threads::topology const>>, boost::_bi::value<std::reference_wrapper<boost::barrier>>>>>::run	thread.hpp	116	0x7ffff63a0ef2	
31	thread_proxy			0x7ffff534954d	
32	start_thread	/usr/lib/debug/.build-id/4d/7f52f335dc9665c2dcf308ce6514a6ae86dede.debug	333	0x7ffff51206ba	
33	clone	/usr/lib/debug/lib/x86_64-linux-gnu/libc-2.23.so	109	0x7ffff467182d	

It seems like while trying to create work (stack level #6), `hpx::util::thread_description::data_type` is expected to have a valid member `data_`, but that is not the case. `HPX_THROWS_IF` is then called:

`if (!data.description)
        {
            HPX_THROWS_IF(ec, bad_parameter,
                "thread::detail::create_work", "description is nullptr");
            return;
        }`

Any idea what might be going on?

**Comment by khuck** [comment]
Is this with the Debug CMake configuration? If so, it's been known for a while - I think there is an assertion in there that doesn't get tripped by the RelWithDebInfo configuration. It's somewhere in the HPX code, and I haven't been able to resolve it.  In the meantime, if you need Debug information, you should use the RelWithDebInfo CMake configuration instead (for now).

**Comment by khuck** [comment]
@nchaimov fixed this with commit 52946865461b79ecf38de512aa3028423a17fcd9
