### ISSUE TITLE
Apex can not automatically install Active harmony

### ISSUE THREAD

**Issue by justwagle** [khuck/xpress-apex#84]
In case path for Active Harmony is not provied in cmake, APEX tries to download and build active harmony but fails with the following error. 

[  7%] Performing download step (download, verify and extract) for 'project_activeharmony'
-- project_activeharmony download command succeeded.  See also /Files/Packages/hpxapex/build/apex/src/apex/activeharmony-4.6.0/src/project_activeharmony-stamp/project_activeharmony-download-*.log
[  7%] No patch step for 'project_activeharmony'
[  7%] No update step for 'project_activeharmony'
[  7%] No configure step for 'project_activeharmony'
[  7%] Performing build step for 'project_activeharmony'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[  7%] Linking CXX static library ../lib/libhpx_init.a
[  7%] Built target hpx_init
hcfg.c: In function ‘hcfg_parse’:
hcfg.c:353:11: error: ‘keyval’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     char* keyval;
           ^~~~~~

The complete error log along with the script I used for building is found here:
https://gist.github.com/justwagle/4450a8f7bad19d366ffe8facbfcf0cda

**Comment by khuck** [comment]
I don't control the ActiveHarmony source code, so you'll have to build ActiveHarmony separately - it's pretty easy:

wget http://www.dyninst.org/sites/default/files/downloads/harmony/ah-4.6.0.tar.gz
tar -xvzf ah-4.6.0.tar.gz
cd activeharmony-4.6
export CC=gcc
export CXX=g++
export CFLAGS="-fPIC"
export CXXFLAGS="-fPIC -fpermissive"
export LDFLAGS=-fPIC

make MPICC=mpicc_disabled
prefix=/usr/local/packages/activeharmony/4.6.0-gcc   # or wherever you want it installed
make MPICC=mpicc_disabled install prefix=$prefix
