### ISSUE TITLE
make test gives errors

### ISSUE THREAD

**Issue by viraj96** [khuck/xpress-apex#87]
Hi,

I successfully compiled the project on my system. But it seems that the tests are not compiled. Precisely when I do `make tests` it shows me that all 82 tests failed to excecute citing multiple binaries that were not found. 

While installing the library itself, I followed the documentation and used the following major commands 

```
sudo cmake -DBOOST_ROOT=/usr/local/lib  -DCMAKE_INSTALL_PREFIX=/usr/local/lib/apex -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
sudo make
sudo make install
```

Does anybody have any ideas?

**Comment by khuck** [comment]
Apologies, the documentation is woefully out of date.  Boost is no longer needed.  You should be able to get a good simple configuration of APEX with these options:

```bash
cmake .. \
-DBUILD_EXAMPLES=TRUE \
-DBUILD_TESTS=TRUE \
-DCMAKE_INSTALL_PREFIX=. \
-DCMAKE_BUILD_TYPE=Release \
```

You may also want to use the "develop" branch, some recent changes improve performance and stability.  I'll be updating the documentation as time allows, hopefully within the month.  Thanks!
